name: Convert IPYNB to PDF

on:
  push:
    branches:
      - main

jobs:
  convert_notebooks_to_pdf:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.8"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install nbconvert
          pip install jupyter

      - name: Install Pandoc and TeX Live
        run: |
          sudo apt-get update
          sudo apt-get install -y pandoc texlive-xetex texlive-fonts-recommended texlive-generic-recommended

      - name: Convert IPYNB to PDF
        run: |
          mkdir -p pdfs
          for notebook in *.ipynb; do
            jupyter nbconvert --to pdf "$notebook" --output-dir=pdfs
          done

      - name: Upload PDFs as artifacts
        uses: actions/upload-artifact@v3
        with:
          name: pdfs
          path: pdfs/*.pdf
